const carData = [
    {
        id: 129031,
        brand: "BMW",
        model: "3 Series",
        bodystyle: "sedan",
        Image: "bmw3.png",
        year: 2021,
        trim: "M340i xDrive AWD",
        mpg: 26,
        horsepower: 382,
        engine: "EL H6",
        transmission: "Automatic",
        drivetrain: "All-Wheel Drive",
        fueltype: "Gasoline",
        acc: 4.1,
        fuelcap: 15.6,
        Price: 53000,
    },
    {
        id: 987654,
        brand: "Tesla",
        model: "Model S",
        bodystyle: "hatchback",
        Image: "tesla_model_s.png",
        year: 2022,
        trim: "Long Range Plus",
        mpg: "None",
        horsepower: 670,
        engine: "Electric",
        transmission: "Automatic",
        drivetrain: "All-Wheel Drive",
        fueltype: "Electric",
        acc: 2.4,
        fuelcap: "N/A",
        Price: 79990,
    },
    {
        id: 456789,
        brand: "Toyota",
        model: "Camry",
        bodystyle: "sedan",
        Image: "toyota_camry.png",
        year: 2020,
        trim: "XSE V6",
        mpg: 26,
        horsepower: 301,
        engine: "V6",
        transmission: "8-Speed Automatic",
        drivetrain: "Front-Wheel Drive",
        fueltype: "Gasoline",
        acc: 5.8,
        fuelcap: 16,
        Price: 34850,
    },
    {
        id: 789012,
        brand: "Chevrolet",
        model: "Camaro",
        bodystyle: "coupe",
        Image: "chevrolet_camaro.png",
        year: 2022,
        trim: "SS",
        mpg: 20,
        horsepower: 455,
        engine: "V8",
        transmission: "10-Speed Automatic",
        drivetrain: "Rear-Wheel Drive",
        fueltype: "Gasoline",
        acc: 4.0,
        fuelcap: 19,
        Price: 42995,
    },
    {
        id: 345678,
        brand: "Ford",
        model: "Mustang",
        bodystyle: "convertible",
        Image: "ford_mustang.png",
        year: 2023,
        trim: "GT Premium",
        mpg: 18,
        horsepower: 450,
        engine: "V8",
        transmission: "6-Speed Manual",
        drivetrain: "Rear-Wheel Drive",
        fueltype: "Gasoline",
        acc: 4.5,
        fuelcap: 16,
        Price: 44990,
    }
];
